-- Add popular international recipes (fixed)

INSERT INTO public.recipes (title, description, image_url, prep_time, cook_time, servings, difficulty, category, ingredients, instructions, tags) VALUES
-- Italian Cuisine
('Spaghetti Carbonara', 'Classic Roman pasta with eggs, cheese, and guanciale', 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800', 10, 15, 4, 'medium', 'Italian', ARRAY['400g spaghetti', '200g guanciale', '4 eggs', '100g Pecorino Romano', 'black pepper', 'salt'], ARRAY['Boil pasta in salted water', 'Dice and fry guanciale until crispy', 'Beat eggs with grated cheese', 'Mix hot pasta with guanciale', 'Add egg mixture off heat, toss quickly', 'Season with black pepper'], ARRAY['pasta', 'italian', 'quick']),
('Margherita Pizza', 'Traditional Neapolitan pizza with tomato, mozzarella, and basil', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800', 120, 12, 2, 'medium', 'Italian', ARRAY['pizza dough', '200g San Marzano tomatoes', '250g fresh mozzarella', 'fresh basil', 'olive oil', 'salt'], ARRAY['Prepare and rest pizza dough', 'Stretch dough into round shape', 'Spread crushed tomatoes', 'Add torn mozzarella', 'Bake at 250C for 10-12 minutes', 'Garnish with fresh basil'], ARRAY['pizza', 'vegetarian', 'italian']),
('Risotto alla Milanese', 'Creamy saffron risotto from Milan', 'https://images.unsplash.com/photo-1633964913295-ceb43826833f?w=800', 10, 30, 4, 'medium', 'Italian', ARRAY['320g Arborio rice', '1L chicken stock', '1 onion', '100ml white wine', 'saffron threads', '80g Parmesan', '60g butter'], ARRAY['Toast saffron in warm stock', 'Sauté diced onion in butter', 'Add rice, toast 2 minutes', 'Add wine, let evaporate', 'Add stock ladle by ladle, stirring', 'Finish with butter and Parmesan'], ARRAY['risotto', 'italian', 'comfort food']),

-- Chinese Cuisine
('Fried Rice', 'Classic Chinese fried rice with vegetables and eggs', 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800', 10, 10, 4, 'easy', 'Chinese', ARRAY['4 cups cooked rice', '3 eggs', '1 cup mixed vegetables', '3 tbsp soy sauce', '2 cloves garlic', 'green onions', 'sesame oil'], ARRAY['Scramble eggs, set aside', 'Stir-fry vegetables and garlic', 'Add cold rice, break up clumps', 'Add soy sauce and sesame oil', 'Mix in scrambled eggs', 'Garnish with green onions'], ARRAY['rice', 'chinese', 'quick', 'vegetarian']),
('Kung Pao Chicken', 'Spicy Sichuan stir-fry with peanuts', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800', 20, 10, 4, 'medium', 'Chinese', ARRAY['500g chicken breast', '1 cup roasted peanuts', '4 dried chilies', '2 tbsp Sichuan peppercorns', 'soy sauce', 'rice vinegar', 'cornstarch', 'ginger', 'garlic'], ARRAY['Marinate diced chicken in soy sauce', 'Prepare sauce with vinegar and cornstarch', 'Stir-fry chilies and peppercorns', 'Add chicken, cook until golden', 'Add sauce and peanuts', 'Toss and serve hot'], ARRAY['spicy', 'chinese', 'chicken']),
('Dumplings (Jiaozi)', 'Traditional Chinese dumplings with pork filling', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800', 45, 15, 6, 'hard', 'Chinese', ARRAY['dumpling wrappers', '400g ground pork', '2 cups napa cabbage', '2 tbsp soy sauce', 'ginger', 'garlic', 'sesame oil', 'green onions'], ARRAY['Mix pork with chopped cabbage, seasonings', 'Place filling in center of wrapper', 'Fold and pleat edges to seal', 'Boil in water for 6-8 minutes', 'Or pan-fry for crispy bottom', 'Serve with dipping sauce'], ARRAY['dumplings', 'chinese', 'traditional']);
