-- Add more international recipes - Indian, Mexican, Japanese

INSERT INTO public.recipes (title, description, image_url, prep_time, cook_time, servings, difficulty, category, ingredients, instructions, tags) VALUES
-- Indian Cuisine
('Chicken Tikka Masala', 'Creamy tomato-based curry with marinated chicken', 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800', 30, 30, 6, 'medium', 'Indian', ARRAY['800g chicken', '1 cup yogurt', 'tikka masala spice mix', '400g tomatoes', '200ml cream', 'onions', 'ginger', 'garlic', 'garam masala'], ARRAY['Marinate chicken in yogurt and spices', 'Grill or bake chicken pieces', 'Sauté onions, ginger, garlic', 'Add tomatoes and spices', 'Simmer with cream', 'Add chicken, cook 10 minutes'], ARRAY['curry', 'indian', 'chicken', 'creamy']),
('Vegetable Biryani', 'Fragrant rice dish with mixed vegetables and spices', 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800', 30, 45, 6, 'medium', 'Indian', ARRAY['2 cups basmati rice', 'mixed vegetables', 'onions', 'tomatoes', '1 cup yogurt', 'biryani masala', 'saffron', 'mint', 'cilantro', 'ghee'], ARRAY['Soak rice for 30 minutes', 'Layer fried onions, vegetables, spices', 'Cook rice separately until 70% done', 'Layer rice over vegetables', 'Add saffron milk and fried onions', 'Cook on low heat for 20 minutes'], ARRAY['rice', 'indian', 'vegetarian', 'aromatic']),
('Palak Paneer', 'Spinach curry with Indian cottage cheese', 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800', 15, 25, 4, 'medium', 'Indian', ARRAY['500g spinach', '250g paneer', '2 onions', '2 tomatoes', 'ginger-garlic paste', 'cream', 'cumin', 'garam masala', 'chili powder'], ARRAY['Blanch spinach, blend to puree', 'Fry paneer cubes until golden', 'Sauté onions, ginger-garlic', 'Add tomatoes and spices', 'Mix in spinach puree', 'Add paneer and cream, simmer'], ARRAY['vegetarian', 'indian', 'healthy', 'curry']),

-- Mexican Cuisine  
('Tacos al Pastor', 'Mexican tacos with marinated pork and pineapple', 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800', 240, 15, 6, 'medium', 'Mexican', ARRAY['1kg pork shoulder', 'pineapple', 'dried chilies', 'achiote paste', 'onion', 'cilantro', 'lime', 'corn tortillas'], ARRAY['Marinate pork in chili-achiote paste overnight', 'Grill or roast pork until charred', 'Slice thinly', 'Grill pineapple slices', 'Warm tortillas', 'Assemble with pork, pineapple, onion, cilantro'], ARRAY['tacos', 'mexican', 'pork', 'street food']),
('Chicken Enchiladas', 'Rolled tortillas with chicken in chili sauce', 'https://images.unsplash.com/photo-1599974718900-ddaa6cabf72e?w=800', 20, 30, 6, 'medium', 'Mexican', ARRAY['12 corn tortillas', '500g shredded chicken', 'enchilada sauce', '2 cups cheese', 'onions', 'sour cream', 'cilantro'], ARRAY['Prepare enchilada sauce', 'Mix chicken with cheese and onions', 'Dip tortillas in sauce', 'Fill with chicken mixture, roll', 'Place in baking dish, cover with sauce', 'Top with cheese, bake 25 minutes'], ARRAY['enchiladas', 'mexican', 'chicken', 'baked']),
('Guacamole', 'Fresh avocado dip with lime and cilantro', 'https://images.unsplash.com/photo-1622421285076-2b32c0f8e6fb?w=800', 10, 0, 6, 'easy', 'Mexican', ARRAY['4 ripe avocados', '1 lime', '1 tomato', '1 onion', 'jalapeño', 'cilantro', 'salt', 'cumin'], ARRAY['Mash avocados in bowl', 'Add lime juice immediately', 'Mix in diced tomato, onion, jalapeño', 'Add chopped cilantro', 'Season with salt and cumin', 'Serve immediately'], ARRAY['dip', 'mexican', 'vegetarian', 'vegan', 'quick']),

-- Japanese Cuisine
('Chicken Teriyaki', 'Glazed chicken with sweet-savory teriyaki sauce', 'https://images.unsplash.com/photo-1600628421055-4d30de868b8f?w=800', 15, 15, 4, 'easy', 'Japanese', ARRAY['4 chicken thighs', '4 tbsp soy sauce', '2 tbsp mirin', '2 tbsp sake', '1 tbsp sugar', 'ginger', 'sesame seeds'], ARRAY['Mix soy sauce, mirin, sake, sugar for sauce', 'Pan-fry chicken skin-side down', 'Flip when golden brown', 'Add sauce to pan', 'Simmer until glazed and sticky', 'Garnish with sesame seeds'], ARRAY['japanese', 'chicken', 'quick', 'glazed']),
('Miso Ramen', 'Rich noodle soup with miso broth', 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=800', 20, 40, 4, 'medium', 'Japanese', ARRAY['ramen noodles', '1L chicken stock', '3 tbsp miso paste', 'pork belly', 'soft-boiled eggs', 'green onions', 'nori', 'bamboo shoots'], ARRAY['Simmer stock with miso paste', 'Cook pork belly until tender', 'Boil eggs for 6 minutes', 'Cook ramen noodles', 'Assemble: noodles, broth, toppings', 'Garnish with nori and green onions'], ARRAY['ramen', 'japanese', 'noodles', 'soup']),
('Tempura', 'Light and crispy battered vegetables and seafood', 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800', 20, 15, 4, 'medium', 'Japanese', ARRAY['shrimp', 'sweet potato', 'zucchini', 'eggplant', '1 cup flour', 'ice water', '1 egg', 'oil for frying'], ARRAY['Prepare vegetables and shrimp', 'Mix flour, egg, ice water lightly', 'Heat oil to 180C', 'Dip ingredients in batter', 'Fry until golden and crispy', 'Serve with tentsuyu sauce'], ARRAY['tempura', 'japanese', 'fried', 'crispy']);